site_name: Ezi-Servo Plus-R/E

nav:
  - 홈: README.md
  - Plus-R: 
    - 개요: README_R.md
  - Plus-E: 
    - 개요: README_E.md
  - 예제: 
    - Plus-R 예제:
      - 01.ConnectionExam: doc-R1.md
      - 02.ParameterTestExam: doc-R2.md
      - 03.InputPinControlExam: doc-R3.md
      - 04.OutputPinControlExam: doc-R4.md
      - 05.JogMovementExam: doc-R5.md
      - 06.JogMovementExExam: doc-R6.md
      - 07.MoveAbsIncPosExam: doc-R7.md
      - 08.MoveAbsIncPosExExam: doc-R8.md
      - 09.PositionOverrideExam: doc-R9.md
      - 10.VelocityOverrideExam: doc-R10.md
    - Plus-E 예제:
      - 01.ConnectionExam: doc-E1.md
      - 02.ParameterTestExam: doc-E2.md
      - 03.InputPinControlExam: doc-E3.md
      - 04.OutputPinControlExam: doc-E4.md
      - 05.JogMovementExam: doc-E5.md
      - 06.JogMovementExExam: doc-E6.md
      - 07.MoveAbsIncPosExam: doc-E7.md
      - 08.MoveAbsIncPosExExam: doc-E8.md
      - 09.PositionOverrideExam: doc-E9.md
      - 10.VelocityOverrideExam: doc-E10.md

theme:
  name: material
  logo: FASTECH.png
  palette:
    primary: yellow
    accent: black

copyright: Copyright &copy; 2025 FASTECH



plugins:
  - offline
  - search

extra:
  manifest: manifest.webmanifest

extra_javascript:
  - sw-register.js

