[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && mkdocs build && node generateFileList.js"
  publish = "site"

[[headers]]
  for = "/search/search_index.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
